### PR TITLE
Make modules load lazily

### PR DESCRIPTION
**Pull request by frangio**
This mitigates issues like #40.

### CODE REVIEW

**Comment by nventuro** [comment]
Why is this a draft?

**Comment by frangio** [comment]
I wanted to think about it a bit more. :slightly_smiling_face:

**Comment by nventuro** [comment]
Why wasn't a CI run triggered? Looks like a bug in GitHub :/

**Comment by nventuro** [comment]
That did it.

**Comment by nventuro** [comment]
Integration tests passed so I'm happy. Thanks!

**Pull request merged**
