### PR TITLE
Use 'eql' instead of 'equal' for assertion to support array types

### PR DESCRIPTION
**Pull request by forshtat**
The emitted array is a different instance in JavaScript's eyes, yet the
expected behavior would be to accept it as equal.
The 'eql' assertion is supposed to do just that.

### CODE REVIEW

**Comment by forshtat** [comment]
I see there is a more advanced PR on this topic, but that one seems to be stalled for a while. This one is a very minimal change.

**Comment by nventuro** [comment]
This is an easy win, yes, though arrays of BNs will still not be supported sadly. Two small comments:

1. Can you add the test function to the old EventEmitter instead of creating a new one? (or is there a reason to do it this way?)
2. Can you change `eql` for `deep.equal`? I worry that people not familiar with chai won't notice that `equal` and `eql` are very different.

**Comment by forshtat** [comment]
> This is an easy win, yes, though arrays of BNs will still not be supported sadly. Thanks a lot once more @forshtat!
> 
> Two small comments:
> 
> 1. Can you add the test function to the old EventEmitter instead of creating a new one? (or is there a reason to do it this way?)
> 2. Can you change `eql` for `deep.equal`? I worry that people not familiar with chai won't notice that `equal` and `eql` are very different.

Done 😃

**Comment by limestoneinsure** [comment]
When will this be published?

```
      it('accepts emitted events with correct string array', async function () {
        await expectEvent.inConstruction(this.emitterV2, 'StringArray',
          { value: this.constructionValuesV2.stringsArray });
      });
```

**Pull request merged**
