### PR TITLE
Don't warn about Ganache's version if not used

### PR DESCRIPTION
**Pull request by alcuadrado**
This PR disables the Ganache version warning if Ganache isn't used.

I couldn't find any test related to this warning, so this PR has no tests either :(

### CODE REVIEW

**Comment by nventuro** [comment]
I think there's value in issuing a warning on non-ganache blockchains, since the helper is not being able to perform it's full job (e.g. an assertion with a wrong revert reason that would revert on ganache would not do so in other environments). 

Perhaps we could instead only output the warning a single time, instead of on every `expectRevert` call?

**Comment by frangio** [comment]
I think I agree with @nventuro here. We should show the warning but only once.

**Comment by alcuadrado** [comment]
> I think there's value in issuing a warning on non-ganache blockchains, since the helper is not being able to perform its full job (e.g. an assertion with a wrong revert reason that would revert on ganache would succeed in other environments).

I don't follow. Which warning? How can you be sure that it doesn't support revert reasons?


To my knowledge, the only node that returns errors on transaction failures is Ganache, so using `expectRevert` with other nodes today would always fail on

```js
expect.fail('Expected an exception but none was received');
```

If `expectRevert` doesn't fail because of that, and isn't running against Ganache, why would you assume that the node doesn't support revert reasons?

**Comment by frangio** [comment]
Good points...

So `expectRevert` is useless on Geth? In that case showing a warning or not is the least of troubles, all of the assertions would be failing.

**Comment by nventuro** [comment]
>How can you be sure that it doesn't support revert reasons?

I'd rather whitelist nodes that we know support them, rather than assume they do.

>To my knowledge, the only node that returns errors on transaction failures is Ganache, so using expectRevert with other nodes today would always fail

I agree with @frangio, if this is the case then we should emit a warning stating this.

**Comment by nventuro** [comment]
Superceded by #80

**Pull request closed without merging**
