### PR TITLE
Add 'key' field to the 'expectEvent' assertion error message

### PR DESCRIPTION
**Pull request by forshtat**
If the 'key' is included, test output is not very informative for comlex
events.

### CODE REVIEW

**Comment by frangio** [comment]
Hi @forshtat! I think this is a great idea.

I think I prefer the following error message. Can you change it?

`expected event argument '${key}' to have value ${value} but got ${args[key]}`

**Comment by forshtat** [comment]
@frangio Changed!)

**Comment by nventuro** [comment]
@forshtat did you try these out? I wanted to look at the actual error message, but Chai seems to be ignoring the messages we're provoding.

**Comment by forshtat** [comment]
I am sure it worked for me when I made a change, I had modified version installed in my node_modules and revert messages were helpful. I will look into it first thing tomorrow morning. Will add some tests on the error message I guess.

**Comment by forshtat** [comment]
> @forshtat did you try these out? I wanted to look at the actual error message, but Chai seems to be ignoring the messages we're providing.

You are right, the chai-bn would ignore the custom message given.
Addressed it in 
https://github.com/OpenZeppelin/chai-bn/pull/9

**Comment by forshtat** [comment]
@nventuro also, after publishing pached chai-bn you could merge https://github.com/OpenZeppelin/openzeppelin-test-helpers/pull/109

**Pull request merged**
